/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/blue-dynamic.component';
const styles_BlueDynamicComponent:any[] = ([] as any[]);
export const RenderType_BlueDynamicComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_BlueDynamicComponent,
  data: {}
}
);
export function View_BlueDynamicComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',[
      [
        'class',
        'img-rounded'
      ]
      ,
      [
        'style',
        'background-color: lightskyblue;margin: 5px'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[' Blue Dynamic Component! ']))
  ]
  ,(null as any),(null as any));
}
function View_BlueDynamicComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'dynamic-component',([] as any[]),(null as any),(null as any),(null as any),View_BlueDynamicComponent_0,RenderType_BlueDynamicComponent)),
    import0.ɵdid(24576,(null as any),0,import1.BlueDynamicComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const BlueDynamicComponentNgFactory:import0.ComponentFactory<import1.BlueDynamicComponent> = import0.ɵccf('dynamic-component',import1.BlueDynamicComponent,View_BlueDynamicComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2ppdGVuZHJha2FzYXVkaGFuL0Rlc2t0b3Avd29ya3NwYWNlL2FuZ3VsYXJfNF9hb3Rfd2l0aF9jb21wb25lbnRfZmFjdG9yeV9yZXNvbHZlci9zcmMvYXBwL2JsdWUtZHluYW1pYy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvaml0ZW5kcmFrYXNhdWRoYW4vRGVza3RvcC93b3Jrc3BhY2UvYW5ndWxhcl80X2FvdF93aXRoX2NvbXBvbmVudF9mYWN0b3J5X3Jlc29sdmVyL3NyYy9hcHAvYmx1ZS1keW5hbWljLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2ppdGVuZHJha2FzYXVkaGFuL0Rlc2t0b3Avd29ya3NwYWNlL2FuZ3VsYXJfNF9hb3Rfd2l0aF9jb21wb25lbnRfZmFjdG9yeV9yZXNvbHZlci9zcmMvYXBwL2JsdWUtZHluYW1pYy5jb21wb25lbnQudHMuQmx1ZUR5bmFtaWNDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2ppdGVuZHJha2FzYXVkaGFuL0Rlc2t0b3Avd29ya3NwYWNlL2FuZ3VsYXJfNF9hb3Rfd2l0aF9jb21wb25lbnRfZmFjdG9yeV9yZXNvbHZlci9zcmMvYXBwL2JsdWUtZHluYW1pYy5jb21wb25lbnQudHMuQmx1ZUR5bmFtaWNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiaW1nLXJvdW5kZWRcIiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IGxpZ2h0c2t5Ymx1ZTttYXJnaW46IDVweFwiPiBCbHVlIER5bmFtaWMgQ29tcG9uZW50ISA8L2Rpdj4iLCI8ZHluYW1pYy1jb21wb25lbnQ+PC9keW5hbWljLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQTRFOzs7Ozs7SUNBNUU7Z0JBQUE7Ozs7In0=
