/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/green-dynamic.component';
const styles_GreenDynamicComponent:any[] = ([] as any[]);
export const RenderType_GreenDynamicComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_GreenDynamicComponent,
  data: {}
}
);
export function View_GreenDynamicComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',[
      [
        'class',
        'img-rounded'
      ]
      ,
      [
        'style',
        'background-color: lightgreen;margin: 5px'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[' Green Dynamic Component! ']))
  ]
  ,(null as any),(null as any));
}
function View_GreenDynamicComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'dynamic-component',([] as any[]),(null as any),(null as any),(null as any),View_GreenDynamicComponent_0,RenderType_GreenDynamicComponent)),
    import0.ɵdid(24576,(null as any),0,import1.GreenDynamicComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const GreenDynamicComponentNgFactory:import0.ComponentFactory<import1.GreenDynamicComponent> = import0.ɵccf('dynamic-component',import1.GreenDynamicComponent,View_GreenDynamicComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2ppdGVuZHJha2FzYXVkaGFuL0Rlc2t0b3Avd29ya3NwYWNlL2FuZ3VsYXJfNF9hb3Rfd2l0aF9jb21wb25lbnRfZmFjdG9yeV9yZXNvbHZlci9zcmMvYXBwL2dyZWVuLWR5bmFtaWMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2ppdGVuZHJha2FzYXVkaGFuL0Rlc2t0b3Avd29ya3NwYWNlL2FuZ3VsYXJfNF9hb3Rfd2l0aF9jb21wb25lbnRfZmFjdG9yeV9yZXNvbHZlci9zcmMvYXBwL2dyZWVuLWR5bmFtaWMuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvaml0ZW5kcmFrYXNhdWRoYW4vRGVza3RvcC93b3Jrc3BhY2UvYW5ndWxhcl80X2FvdF93aXRoX2NvbXBvbmVudF9mYWN0b3J5X3Jlc29sdmVyL3NyYy9hcHAvZ3JlZW4tZHluYW1pYy5jb21wb25lbnQudHMuR3JlZW5EeW5hbWljQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9qaXRlbmRyYWthc2F1ZGhhbi9EZXNrdG9wL3dvcmtzcGFjZS9hbmd1bGFyXzRfYW90X3dpdGhfY29tcG9uZW50X2ZhY3RvcnlfcmVzb2x2ZXIvc3JjL2FwcC9ncmVlbi1keW5hbWljLmNvbXBvbmVudC50cy5HcmVlbkR5bmFtaWNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiaW1nLXJvdW5kZWRcIiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IGxpZ2h0Z3JlZW47bWFyZ2luOiA1cHhcIj4gR3JlZW4gRHluYW1pYyBDb21wb25lbnQhIDwvZGl2PiIsIjxkeW5hbWljLWNvbXBvbmVudD48L2R5bmFtaWMtY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFBMEU7Ozs7OztJQ0ExRTtnQkFBQTs7OzsifQ==
