/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/red-dynamic.component';
const styles_RedDynamicComponent:any[] = ([] as any[]);
export const RenderType_RedDynamicComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_RedDynamicComponent,
  data: {}
}
);
export function View_RedDynamicComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',[
      [
        'class',
        'img-rounded'
      ]
      ,
      [
        'style',
        'background-color: lightcoral;margin: 5px'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[' Red Dynamic Component! ']))
  ]
  ,(null as any),(null as any));
}
function View_RedDynamicComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'dynamic-component',([] as any[]),(null as any),(null as any),(null as any),View_RedDynamicComponent_0,RenderType_RedDynamicComponent)),
    import0.ɵdid(24576,(null as any),0,import1.RedDynamicComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const RedDynamicComponentNgFactory:import0.ComponentFactory<import1.RedDynamicComponent> = import0.ɵccf('dynamic-component',import1.RedDynamicComponent,View_RedDynamicComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2ppdGVuZHJha2FzYXVkaGFuL0Rlc2t0b3Avd29ya3NwYWNlL2FuZ3VsYXJfNF9hb3Rfd2l0aF9jb21wb25lbnRfZmFjdG9yeV9yZXNvbHZlci9zcmMvYXBwL3JlZC1keW5hbWljLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qaXRlbmRyYWthc2F1ZGhhbi9EZXNrdG9wL3dvcmtzcGFjZS9hbmd1bGFyXzRfYW90X3dpdGhfY29tcG9uZW50X2ZhY3RvcnlfcmVzb2x2ZXIvc3JjL2FwcC9yZWQtZHluYW1pYy5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9qaXRlbmRyYWthc2F1ZGhhbi9EZXNrdG9wL3dvcmtzcGFjZS9hbmd1bGFyXzRfYW90X3dpdGhfY29tcG9uZW50X2ZhY3RvcnlfcmVzb2x2ZXIvc3JjL2FwcC9yZWQtZHluYW1pYy5jb21wb25lbnQudHMuUmVkRHluYW1pY0NvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvaml0ZW5kcmFrYXNhdWRoYW4vRGVza3RvcC93b3Jrc3BhY2UvYW5ndWxhcl80X2FvdF93aXRoX2NvbXBvbmVudF9mYWN0b3J5X3Jlc29sdmVyL3NyYy9hcHAvcmVkLWR5bmFtaWMuY29tcG9uZW50LnRzLlJlZER5bmFtaWNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiaW1nLXJvdW5kZWRcIiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IGxpZ2h0Y29yYWw7bWFyZ2luOiA1cHhcIj4gUmVkIER5bmFtaWMgQ29tcG9uZW50ISA8L2Rpdj4iLCI8ZHluYW1pYy1jb21wb25lbnQ+PC9keW5hbWljLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQTBFOzs7Ozs7SUNBMUU7Z0JBQUE7Ozs7In0=
